### PR TITLE
Check bazelisk exists

### LINKED ISSUE #370: bazeliskNpmPath: should check if @bazel/bazelisk binary exists?
I recently had an issue where if I run `@bazel/ibazel` using `yarn ibazel` (or `npn bazel`) it would attempt to locate `@bazel/bazelisk` (and fail) even though I did not install  `@bazel/bazelisk`.

## Steps to reproduce

Assuming `bazel` is already in `PATH`. 

1. Create an empty directory
2. Run `yarn init`
3. Run `yarn install -D @bazel/ibazel`
4. Add dummy BUILD and WORKSPACE
5. Run `yarn ibazel build //...`

Expected result: build succeeds

Actual result:
```
$ yarn ibazel build //...
yarn run v1.13.0
$ /private/tmp/bazelisk/node_modules/.bin/ibazel build //...
iBazel [2:56AM]: Error getting Bazel info fork/exec /private/tmp/bazelisk/node_modules/@bazel/bazelisk/bazelisk-darwin_amd64: no such file or directory
iBazel [2:56AM]: Querying for files to watch...
iBazel [2:56AM]: Bazel query failed: fork/exec /private/tmp/bazelisk/node_modules/@bazel/bazelisk/bazelisk-darwin_amd64: no such file or directory
iBazel [2:56AM]: Bazel query failed: fork/exec /private/tmp/bazelisk/node_modules/@bazel/bazelisk/bazelisk-darwin_amd64: no such file or directory
iBazel [2:56AM]: Building //...
iBazel [2:56AM]: Build error: fork/exec /private/tmp/bazelisk/node_modules/@bazel/bazelisk/bazelisk-darwin_amd64: no such file or directory
iBazel [2:56AM]: Error reading config: open .bazel_fix_commands.json: no such file or directory
iBazel [2:56AM]: Use default regex
^C
```

Looking at  https://github.com/bazelbuild/bazel-watcher/blob/d7c0cc4b198dfe76039491dd13a0c6d24c9bf2f2/bazel/bazel.go#L72, it seems that the code only builds the path for `node_modules/@bazel/bazelisk/bazelizk-darwin_amd64` but does not check if the binary actually exists. 

So the fix should be simply adding a `os.Stat` check?

----
bazel version:
```
Build label: 2.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 3 09:28:15 2020 (1583227695)
Build timestamp: 1583227695
Build timestamp as int: 1583227695
```
iBazel - Version v0.12.3

### PR DESCRIPTION
**Pull request by zoidbergwill**
Closes #370

My bad

### CODE REVIEW

**Comment by achew22** [comment]
Huh... This is interesting. I don't seem to have any permissions in the repo any more?

Investigating

**Comment by achew22** [comment]
@laurentlb, @jin, @alexeagle I'm not sure how to progress here. When I was offboarded from Google I lost all permissions on this repo. Is it possible to invite me back so I can continue work on this, or is the project dead because I'm not longer employed by Google?

**Comment by jin** [comment]
Hm, I don't have permissions on this project. Did you hand over to any Googler?

cc @philwo

**Comment by achew22** [comment]
No, I didn't hand it over to anyone. Would you like to be a comaintainer on the repo?

**Comment by jin** [comment]
I don't have that much bandwidth for day-to-day maintainership here, nor do I know Go well at this point, so I'm probably not the best candidate for this :) Thanks for the invite though.

@philwo or @aiuto could probably help you regain commit access to this repo.

File: bazel/bazel.go [hunk 1]
```diff
@@ -79,6 +79,13 @@ func bazeliskNpmPath(ibazelBinPath string) (string, error) {
 				ext = ".exe"
 			}
 			name := strings.Join(append(prefix, nm, scope, "bazelisk", "bazelisk-"+bin+ext), "/")
+			_, err := os.Stat(name)
+			if err != nil {
+				if !os.IsNotExist(err) {
+					return "", err
+				}
+				continue
```
Comment (aiuto) [inline bazel/bazel.go:87]: This entire loop seems strange. I it looks like it is taking /a/long/path/like/this/ending/with/node_modules/@bazel/... and we are searching pulling out 5 parts at a time just to check.
Is that so? Why aren't we just scanning for each occurance of  node_modules before assigning the intermedates.

It feels like this  should not be a loop. Simply split the string and look at the last 6 components.
github, alas, does not let me add the comment at line 74, where it belongs.

File: bazel/bazel.go [hunk 2]
```diff
@@ -79,6 +79,13 @@ func bazeliskNpmPath(ibazelBinPath string) (string, error) {
 				ext = ".exe"
 			}
 			name := strings.Join(append(prefix, nm, scope, "bazelisk", "bazelisk-"+bin+ext), "/")
+			_, err := os.Stat(name)
+			if err != nil {
```
Comment (aiuto) [inline bazel/bazel.go:83]: If the file exists but you can not stat it and it is at the end of the path .../node_modules/@bazel/ibazel/bin/<arch>/ibazel, why would continuing matter? Can this occur in practice?
But really, my question is realated the the other comment, which is why this is a loop in the first place.

File: bazel/bazel.go (hunk 1 above)
Comment (zoidbergwill) [reply bazel/bazel.go:87]: Hey @aiuto, thanks for the review. That's a great question. I think it's because bazelisk might be installed as a peer dependency, or as a dependency at a higher level. This code was copied from the `bazelNpmPath`, but I should've factored it out then.

I think it's because, they can be peer dependencies, like:

```
// /DIR/node_modules/@bazel/ibazel/bin/darwin_amd64/ibazel
// /DIR/node_modules/@bazel/bazel-darwin_x64/bazel-0.28.0-darwin-x86_64
```

or ibazel could be a deeper dependency

```
// /DIR/node_modules/DIR_2/node_modules/@bazel/ibazel/bin/darwin_amd64/ibazel
// /DIR/node_modules/@bazel/bazel-darwin_x64/bazel-0.28.0-darwin-x86_64
```

File: bazel/bazel.go (hunk 2 above)
Comment (zoidbergwill) [reply bazel/bazel.go:83]: So I'm continuing if it doesn't exist? And returning the error if we fail to stat the file?

File: bazel/bazel.go (hunk 1 above)
Comment (zoidbergwill) [reply bazel/bazel.go:87]: This isn't really a hot loop, so I don't think the efficiency matters too much, but I'll take a look at doing it with that logic.

**Comment by achew22** [comment]
@jin @aiuto friendly ping on getting merge access for me in this repo again? What is the correct way to go about restoring my status as the sole maintainer?

File: bazel/bazel.go (hunk 1 above)
Comment (achew22) [reply bazel/bazel.go:87]: @aiuto to confirm what @zoidbergwill is flicking at, the recursive nature of NPM's distribution make things... hard to say the least. This code is only invoked once per run and it is worth spending the cycles looping through the filesystem to ensure correct behavior above speed. iBazel is not augmented with telemetry to report on user behavior. Assuming my use is representative (and I know it isn't), I launch iBazel a couple of times over the course of an hour and it remains running for something on the order of 15 minutes with this loop representing an infinitesimally small fraction of that time.

Maybe the action here is to learn from the design decisions of others and not adopt this as a strategy for the core of Bazel. NPM is just too complex.

I presume you spend a great deal of time interacting bazel as a part of your job. Maybe ibazel could be added as a tool in your toolkit. It's not too fancy. It simply rdeps queries the target you want to `build`, `run`, or `test, and watches the inodes of any inputs. When those inodes broadcast that they have changed it reruns `bazel` with the action you have requested on the targets you provided. I'd love to have you try it out and tell me some ways I can improve it. What do you think about that? 

@zoidbergwill, I want to again praise you for contributing to open source software. Thank you for volunteering your time and investing your efforts. For me, knowing that people are using something I built, especially when it's in a way that I didn't anticipate like the TS/JS community is doing, brings me joy. Thank you so much!

Comment (zoidbergwill) [reply bazel/bazel.go:87]: So I tried to simplify it with logic that looked something like the following, but I don't know how much it helps with the readability:

```
+// findAllNodeModules helps us find where bazel/bazelisk might be installed
+// if ibazel lives here:
+// /DIR/node_modules/package_without_namespace/node_modules/@namespace/package/node_modules/@bazel/ibazel/bin/darwin_amd64/ibazel
+// We could find bazel in
+// /DIR/node_modules/@bazel/bazel-darwin_x64/bazel-0.28.0-darwin-x86_64
+// /DIR/node_modules/package_without_namespace/node_modules/@bazel/bazel-darwin_x64/bazel-0.28.0-darwin-x86_64
+// /DIR/node_modules/package_without_namespace/node_modules/@namespace/package/node_modules/@bazel/bazel-darwin_x64/bazel-0.28.0-darwin-x86_64
+func findAllNodeModules(binPath string) []string {
+       var results []string
+       s := strings.Split(binPath, string(os.PathSeparator))
+       for i, c := range s {
+               if c == "node_modules" {
+                       results = append(results, filepath.Join(s[:i]...))
+               }
+       }
+       return results
+}
+
```

**Comment by laurentlb** [comment]
@philwo @dslomov 
Please give back the maintainers rights to @achew22.

**Comment by jin** [comment]
@aiuto, you have owners perms over the bazelbuild GH org, right? Could you re-grant @achew22 permissions for this repo?

**Comment by aiuto** [comment]
> @aiuto, you have owners perms over the bazelbuild GH org, right? Could you re-grant @achew22 permissions for this repo?

Done. @achew22 Check for an invitation.

File: bazel/bazel.go (hunk 2 above)
Comment (aiuto) [reply bazel/bazel.go:83]: Maybe I'm confused by the example.  Can the match at line 76 ever happen more than once?
It seems like once we find   .../node_modules/@bazel/ibazel/bin/bazilisk then the method should either return success or failure.

Comment (achew22) [reply bazel/bazel.go:83]: @aiuto yes, the match can occur multiple times. It can happen once for each nested `node_modules`. Can you help me understand a bit better the situation where you think it will continue. Just to make things a little cleaner, here is the snippet embedded without comments:

https://github.com/bazelbuild/bazel-watcher/blob/56d637b7562dc74c1b3e5333d2dacd3a8301f64c/bazel/bazel.go#L73-L92

To me, the control flow appears to be:

1. Match on `node_modules/@bazel/ibazel/bin`
1. If `node_modules/@bazel/ibazel/bin/bazilisk` is found, return success. If there is an error return that error.

I'm terribly sorry if I'm being dense here, but I don't see another path through the loop.

Comment (aiuto) [reply bazel/bazel.go:83]: Ah... I understand now. The comments at line 66 made me thing this was a path to a single file, and not something that is more like a shell $PATH.  So I was looking at the loop the wrong way.
Maybe copying a live example into the comment when this code was originally written would have helped.

File: bazel/bazel.go (hunk 1 above)
Comment (aiuto) [reply bazel/bazel.go:87]: I'm fine with either. Again, the lack of an example string in the comment (showing that node_modules can appear many times) threw me off.

**Comment by zoidbergwill** [comment]
I think having a more obvious example, that helps folks understand that the function is something similar to processing a $PATH is a good idea, including some examples like the following in the comment:

```
+// /DIR/node_modules/@bazel/bazel-darwin_x64/bazel-0.28.0-darwin-x86_64
+// /DIR/node_modules/package_without_namespace/node_modules/@bazel/bazel-darwin_x64/bazel-0.28.0-darwin-x86_64
+// /DIR/node_modules/package_without_namespace/node_modules/@namespace/package/node_modules/@bazel/bazel-darwin_x64/bazel-0.28.0-darwin-x86_64
```

**Comment by aiuto** [comment]
RIght.Please add the comment that you think helps.
@achew22 Will you please merge when @zoidbergwill  says it is ready?

**Comment by achew22** [comment]
@aiuto I think there might be some additional step required to grant me permissions. At the bottom of every pull request, for me, the "Merge pull requrest" button is greyed out and it says "You are not [authorized](https://help.github.com/articles/about-protected-branches/) to merge this pull request"

image

Would it be possible for you to go to the settings in this repo and confirm that I'm an admin? Sorry to be such a bother.

**Comment by aiuto** [comment]
It says
Write: Can read, clone, and push to this repository. Can also manage issues and pull requests.

Are you able to do things like set labels on the issue?
Perhaps you have a cached login identity? And have to sign out of github and back in.

**Comment by achew22** [comment]
I just logged in in an incognito window and I have the ability to add labels, but I do not have the ability to merge this pull request. It has the same picture

**Comment by achew22** [comment]
@aiuto can you please make me an admin on the project?

**Comment by aiuto** [comment]
You should not have to be.  rules_nodejs has just write access for all the
outside collaborators and they
approve and merge each other's commits.  Here is one.
https://github.com/bazelbuild/rules_nodejs/pull/1798

I'll merge this one and we can figure out what is going on independently of
this PR.
